readExistingAccounts: false
readExistingProcess: false        # if set, will read the voteMetadata from the JSON instead of creating a new one
stopOnError: false

processInfoFilePath: "./cached-process-info.json"

cspUri: "https://csp-dev.vocdoni.net"                                  # If set, overrides bootnodesUrlRw
cspPublicKey: "03e349c2a4622bd56238616f8160bfeb6b053f260f1a541f72015e0e261ac68d5c"                           # If set, overrides bootnodesUrlRw
cspApiVersion: "v1"


# Either the private key or the wallet/hdPath of the entity
privateKey: "0x0735f7bc73bab5338988c34ebccfd083dab92645d667c59b5617c8d6fb4063da"
mnemonic: ""
hdPath: "m/44'/60'/0'/0/1"
ethNetworkId: "xdai"

vocdoniEnvironment: "prod" # "stg" or "prod"
bootnodesUrlRw: "https://bootnodes.vocdoni.net/gateways.azeno.priv.json"     # Bootnode used by default
dvoteGatewayUri:                                   # If set, overrides bootnodesUrlRw
dvoteGatewayPublicKey:                             # If set, overrides bootnodesUrlRw

numAccounts: 1
maxConcurrency: 1

encryptedVote: true
votesPattern: "all-0"   #  Vote the first option on all questions
#votesPattern: "all-1"  #  Vote the second option on all questions
#votesPattern: "all-2"  #  Vote the third option on all questions
#votesPattern: "all-even"      #  Vote 0 on even voters and 1 on odd voters
#votesPattern: "incremental"   #  Vote 0 on question 0, 1 on question 1, 2 on question 2, etc
