readExistingProcess: false        # if set, will read the voteMetadata from the JSON instead of creating a new one
stopOnError: false

processInfoFilePath: "./cached-process-info.json"

ethNetworkId: "rinkeby"
vocdoniEnvironment: "dev"
tokenAddress: "0x2b7222146a805bba0dbb61869c4b3a03209dffba"
tokenBalanceMappingPosition: 2
privKeys:
- "0x...."
- "0x...."
- "0x...."
- "0x...."
- "0x...."

bootnodesUrlRw: "https://server/gateways.json"     # Bootnode used by default
dvoteGatewayUri:                                   # If set, overrides bootnodesUrlRw
dvoteGatewayPublicKey:                             # If set, overrides bootnodesUrlRw
web3Uri:                                           # If set, overrides bootnodesUrlRw
oracleUri: "https://signaling-oracle.dev.vocdoni.net/dvote"

encryptedVote: true
votesPattern: "all-0"   #  Vote the first option on all questions
#votesPattern: "all-1"  #  Vote the second option on all questions
#votesPattern: "all-2"  #  Vote the third option on all questions
#votesPattern: "all-even"      #  Vote 0 on even voters and 1 on odd voters
#votesPattern: "incremental"   #  Vote 0 on question 0, 1 on question 1, 2 on question 2, etc

